# Generated by Django 6.0 on 2025-12-03 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(db_index=True, max_length=20, unique=True)),
                ('price', models.FloatField(null=True)),
                ('price_change_percent', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('pk', models.CompositePrimaryKey('coin_id', 'transaction_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kline_data', to='coins.coin', to_field='coin')),
            ],
            options={
                'db_table': 'coins_kline',
                'indexes': [models.Index(fields=['coin', '-transaction_time'], name='kline_coin_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'transaction_time'), name='kline_primary_key')],
            },
        ),
    ]
