# Generated by Django 4.2.26 on 2025-11-19 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=8, max_digits=20)),
                ('price_change_percent', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
