# Generated by Django 4.2.26 on 2025-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change_percent',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
