# Generated by Django 6.0 on 2025-12-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_agrigations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('pk', models.CompositePrimaryKey('coin_id', 'transaction_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('bids', models.JSONField()),
                ('asks', models.JSONField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book', to='coins.coin', to_field='coin')),
            ],
            options={
                'db_table': 'coins_orderbook',
                'indexes': [models.Index(fields=['coin', '-transaction_time'], name='orderbook_coin_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'transaction_time'), name='orderbook_primary_key')],
            },
        ),
    ]
