# Generated by Django 4.2.26 on 2025-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_kline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kline',
            name='timestamp',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
