# Generated by Django 6.0 on 2025-12-21 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_materializedOrder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentIndicator',
            fields=[
                ('pk', models.CompositePrimaryKey('coin_id', 'transaction_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('open_interest', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('open_interest_change', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('funding_rate', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('next_funding_time', models.DateTimeField(null=True)),
                ('long_short_ratio', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('long_positions', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('short_positions', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_indicator', to='coins.coin', to_field='coin')),
            ],
            options={
                'db_table': 'sentiment_indicators',
                'indexes': [models.Index(fields=['coin', '-transaction_time'], name='sentiment_indicator_coin_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'transaction_time'), name='sentiment_indicator_primary_key')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalTrigger',
            fields=[
                ('pk', models.CompositePrimaryKey('coin_id', 'transaction_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('ema_20', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('ema_50', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('ema_100', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('ema_200', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('stoch_rsi_k', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('stoch_rsi_d', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('volume_profile_nodes', models.JSONField(help_text='Словарь с ценовыми уровнями и объемами', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_trigger', to='coins.coin', to_field='coin')),
            ],
            options={
                'db_table': 'technical_triggers',
                'indexes': [models.Index(fields=['coin', '-transaction_time'], name='technical_trigger_coin_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'transaction_time'), name='technical_trigger_primary_key')],
            },
        ),
        migrations.CreateModel(
            name='VolatilityLiquidityIndicator',
            fields=[
                ('pk', models.CompositePrimaryKey('coin_id', 'transaction_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('atr_14', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('atr_21', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('vwap', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('vwap_high_band', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('vwap_low_band', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('liquidation_levels', models.JSONField(help_text="Словарь с ключами 'long_levels', 'short_levels'", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volatility_liquidity_indicator', to='coins.coin', to_field='coin')),
            ],
            options={
                'db_table': 'volatility_liquidity_indicators',
                'indexes': [models.Index(fields=['coin', '-transaction_time'], name='volatility_liquidity_indicator_coin_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'transaction_time'), name='volatility_liquidity_indicator_primary_key')],
            },
        ),
    ]
