# Generated by Django 6.0 on 2025-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_sentimentindicator_technicaltrigger_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sentimentindicator',
            name='sentiment_indicator_primary_key',
        ),
        migrations.RemoveConstraint(
            model_name='technicaltrigger',
            name='technical_trigger_primary_key',
        ),
        migrations.RemoveConstraint(
            model_name='volatilityliquidityindicator',
            name='volatility_liquidity_indicator_primary_key',
        ),
        migrations.RenameIndex(
            model_name='sentimentindicator',
            new_name='sentim_coin_ts_idx',
            old_name='sentiment_indicator_coin_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='technicaltrigger',
            new_name='tech_coin_ts_idx',
            old_name='technical_trigger_coin_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='volatilityliquidityindicator',
            new_name='vol_indicator_coin_ts_idx',
            old_name='volatility_liquidity_indicator_coin_ts_idx',
        ),
        migrations.AddConstraint(
            model_name='sentimentindicator',
            constraint=models.UniqueConstraint(fields=('coin', 'transaction_time'), name='sentim_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='technicaltrigger',
            constraint=models.UniqueConstraint(fields=('coin', 'transaction_time'), name='tech_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='volatilityliquidityindicator',
            constraint=models.UniqueConstraint(fields=('coin', 'transaction_time'), name='vol_indicator_primary_key'),
        ),
    ]
